name: Build

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Downloading English YTTD build
        run: curl -Lo yttd.zip https://cdn.vinceh121.me/YourTurnToDie-2023-09-12-01f89eddf5a0e204422984ab574a631c25f3b098fda068bb3eaaa77155e932ac.zip

      - name: Unzipping English YTTD build
        run: unzip yttd.zip -d yttd

      - name: Installing required JavaScript dependencies
        run: npm i
        working-directory: tools

      - name: Compressing fr.json into FR.cte
        run: node tools/compress.js

      - name: Moving FR.cte in yttd/www/languages/
        run: mv FR.cte yttd/www/languages/

      #- name: Editing data/animations.json 2-EN -> 2-FR
      #  run: sed -i 's/EN/FR/' yttd/www/data/Animations.json

      - name: Patching plugins.js
        run: |
          sed -i 's/"LanguageCodes":"\[/"LanguageCodes":"[\\"FR\\",/' yttd/www/js/plugins.js
          sed -i 's/"DefaultLanguage":"EN"/"DefaultLanguage":"FR"/' yttd/www/js/plugins.js

      - name: Patching Animations.json
        run: node tools/apply-animation-patch.mjs

      - name: Patching images
        run: node tools/crypt.js

      - name: Uploading build artefacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: yttd/www

  package:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        include: 
          - platform: win-x64
            archive_ext: zip
          - platform: linux-x64
            archive_ext: tar.gz
          - platform: osx-x64
            archive_ext: zip
          - platform: osx-arm64
            archive_ext: zip
    env:
      NWJS_VERSION: v0.82.0
    steps:
      # GHA can't self-reference a single envvar map https://stackoverflow.com/a/75433159
      - run: |
          echo "NWJS_FOLDER=nwjs-${{ env.NWJS_VERSION }}-${{ matrix.platform }}" >> $GITHUB_ENV
      - run: |
          echo "NWJS_ARCHIVE=${{ env.NWJS_FOLDER }}.${{ matrix.archive_ext }}" >> $GITHUB_ENV
      - run: |
          echo "YTTD_FOLDER=yttd-${{ matrix.platform }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - name: Download artefacts
        uses: actions/download-artifact@v3
      - name: Downloading nwjs
        run: curl --fail -LO https://dl.nwjs.io/${{ env.NWJS_VERSION }}/$NWJS_ARCHIVE

      - name: Extracting nwjs (zip)
        run: unzip -d . $NWJS_ARCHIVE
        if: ${{ matrix.archive_ext == 'zip' }}
      - name: Extracting nwjs (tar.gz)
        run: tar xvf $NWJS_ARCHIVE
        if: ${{ matrix.archive_ext == 'tar.gz' }}

      - run: mv $NWJS_FOLDER $YTTD_FOLDER
      - run: mkdir $YTTD_FOLDER/www
      - run: tar -C $YTTD_FOLDER/www -xvf github-pages/artifact.tar
      - run: cp package.nwjs.json $YTTD_FOLDER/package.json

      - name: Uploading build artefacts
        uses: actions/upload-pages-artifact@v2
        with:
          name: yttd-${{ env.GITHUB_REF_NAME }}-${{ matrix.platform }}
          path: ${{ env.YTTD_FOLDER }}

  deploy:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: package
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploying to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2
